apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: nginx-app
      tier: front-end   
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx:1ap
  replicas: 2
    