apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
    app: front-end
spec:
  type: NodePort
  ports:
      - targetPort: 80
        port: 80
        nodePort: 30008
  selector:
     app: nginx-app
     tier: front-end
    